experiment_parameters:
  mode: multiple images
  num_ellipses: 3

dataset_parameters:
  train:
    path: '../data/svg/generated_images/3_ellipses/train'
    batch_size: 64
    num_images: 10000
  test:
    path: '../data/svg/generated_images/3_ellipses/test'
    batch_size: 64
    num_images: 10

output_stream:
  print_freq: 10
  results_dir: 'results/multiple_images_results/3_ellipses'

train:
  epochs: 1000
  learning_rate: 0.0001
  ellipse_param_to_loss_function:
    cx: MSELoss
    cy: MSELoss
    rx: MSELoss
    ry: MSELoss
    fill: L1Loss
    opacity: MSELoss
    angle: MSELoss
  ellipse_param_to_loss_weight:
    cx: 1.0
    cy: 1.0
    rx: 10.0
    ry: 10.0
    fill: 250.0
    opacity: 100.0
    angle: 30.0


