experiment_parameters:
  mode: single image
  num_ellipses: 5

dataset_parameters:
  train:
    path: '../data/svg/generated_images/5_ellipses/single-test'
    batch_size: 32

output_stream:
  print_freq: 10
  results_dir: 'results/single_image_results/5_ellipses'

train:
  epochs: 100
  learning_rate: 0.0001
  ellipse_param_to_loss_function:
    cx: MSELoss
    cy: MSELoss
    rx: MSELoss
    ry: MSELoss
    fill: L1Loss
    opacity: MSELoss
    angle: MSELoss
  ellipse_param_to_loss_weight:
    cx: 1.0
    cy: 1.0
    rx: 10.0
    ry: 10.0
    fill: 250.0
    opacity: 100.0
    angle: 30.0


